server:
  port: 8080

spring:
  application:
    name: metrics-producer
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  name: metrics-topic

management:
  endpoints:
    web:
      exposure:
        include: metrics